"use client";

import { useCallback, useEffect, useState } from "react";
import { PayoutsPanel } from "./payouts-panel";

// ---------- types ----------

type Plan = {
	id: string;
	title: string;
	price: number;
	productId: string;
	kind: "standard" | "corporate";
	purchaseUrl?: string;
};

type AppState = {
	business: { id: string; title: string; email?: string } | null;
	product: { id: string; title: string } | null;
	plans: Plan[];
	availability: Record<string, string[]>;
	friends: { id: string; name: string; email: string }[];
	ads: {
		id: string;
		headline: string;
		primaryText: string;
		cta: string;
		budget: number;
		link: string;
	}[];
	referrals: { code: string; planId: string; link: string }[];
	config: {
		activeCompanyId: string;
		hasAnthropic: boolean;
		baseUrl: string;
		missingEnv: string[];
	};
};

// ---------- fetch helper ----------

async function api<T = unknown>(
	path: string,
	method: "POST" | "PATCH" | "GET",
	body?: unknown,
): Promise<T> {
	const res = await fetch(path, {
		method,
		headers: body ? { "content-type": "application/json" } : undefined,
		body: body ? JSON.stringify(body) : undefined,
	});
	const data = (await res.json().catch(() => ({}))) as Record<string, unknown>;
	if (!res.ok) {
		const detail = data.detail ? ` — ${JSON.stringify(data.detail)}` : "";
		throw new Error(`${data.error ?? `Request failed (${res.status})`}${detail}`);
	}
	return data as T;
}

function fmtSlot(iso: string): string {
	const d = new Date(iso);
	return Number.isNaN(d.getTime()) ? iso : d.toLocaleString();
}

// ---------- small primitives ----------

function Card({
	num,
	title,
	sub,
	children,
}: {
	num: number;
	title: string;
	sub: string;
	children: React.ReactNode;
}) {
	return (
		<section className="card">
			<h2>
				<span className="step-num">{num}</span>
				{title}
			</h2>
			<p className="sub">{sub}</p>
			{children}
		</section>
	);
}

function Status({ err, ok }: { err?: string | null; ok?: string | null }) {
	if (err) return <div className="alert err">{err}</div>;
	if (ok) return <div className="alert ok">{ok}</div>;
	return null;
}

// A tiny hook to run one async action with busy/error/result state.
function useRun() {
	const [busy, setBusy] = useState(false);
	const [err, setErr] = useState<string | null>(null);
	const run = useCallback(async (fn: () => Promise<void>) => {
		setBusy(true);
		setErr(null);
		try {
			await fn();
		} catch (e) {
			setErr(e instanceof Error ? e.message : String(e));
		} finally {
			setBusy(false);
		}
	}, []);
	return { busy, err, setErr, run };
}

// ---------- steps ----------

function BusinessStep({ s, refresh }: { s: AppState; refresh: () => Promise<void> }) {
	const [title, setTitle] = useState("Shine Mobile Detailing");
	const [email, setEmail] = useState("");
	const { busy, err, run } = useRun();

	return (
		<Card
			num={1}
			title="Create your business"
			sub="POST /accounts (real: companies.create) — spins up a Whop business account."
		>
			{s.business ? (
				<div className="alert ok">
					Business <strong>{s.business.title}</strong> created ·{" "}
					<span className="pill">{s.business.id}</span>
				</div>
			) : (
				<>
					<label>Business name</label>
					<input value={title} onChange={(e) => setTitle(e.target.value)} />
					<label>Contact email (optional)</label>
					<input value={email} onChange={(e) => setEmail(e.target.value)} />
					<button
						disabled={busy}
						onClick={() =>
							run(async () => {
								await api("/api/business", "POST", { title, email });
								await refresh();
							})
						}
					>
						{busy ? "Creating…" : "Create business"}
					</button>
				</>
			)}
			<Status err={err} />
		</Card>
	);
}

function IdeasStep({ hasAnthropic }: { hasAnthropic: boolean }) {
	const [idea, setIdea] = useState("mobile car detailing in Palo Alto");
	const [result, setResult] = useState<{
		source: string;
		supplies: string[];
		plan: string;
		whopResources: { title: string; why: string }[];
	} | null>(null);
	const { busy, err, run } = useRun();

	return (
		<Card
			num={2}
			title="Get a business plan"
			sub={`POST /ideas — ${hasAnthropic ? "generated by Claude" : "static template (set ANTHROPIC_API_KEY for AI)"}.`}
		>
			<label>Your idea</label>
			<textarea value={idea} onChange={(e) => setIdea(e.target.value)} />
			<button
				disabled={busy}
				onClick={() =>
					run(async () => {
						setResult(await api("/api/ideas", "POST", { idea }));
					})
				}
			>
				{busy ? "Thinking…" : "Generate plan"}
			</button>
			<Status err={err} />
			{result && (
				<div style={{ marginTop: 14 }}>
					<span className="badge">{result.source === "claude" ? "AI" : "template"}</span>
					<h3 style={{ fontSize: 14, marginBottom: 4 }}>Supplies to buy</h3>
					<ul className="tight">
						{result.supplies.map((x) => (
							<li key={x}>{x}</li>
						))}
					</ul>
					<h3 style={{ fontSize: 14, marginBottom: 4 }}>Plan</h3>
					<pre className="plan">{result.plan}</pre>
					<h3 style={{ fontSize: 14, marginBottom: 4 }}>Whop resources</h3>
					<ul className="tight">
						{result.whopResources.map((r) => (
							<li key={r.title}>
								<strong>{r.title}</strong> — {r.why}
							</li>
						))}
					</ul>
				</div>
			)}
		</Card>
	);
}

function ProductPlansStep({
	s,
	refresh,
}: {
	s: AppState;
	refresh: () => Promise<void>;
}) {
	const [pTitle, setPTitle] = useState("Mobile Car Detailing");
	const [pDesc, setPDesc] = useState("We come to you — full interior & exterior detail.");
	const [planTitle, setPlanTitle] = useState("Full Detail");
	const [planPrice, setPlanPrice] = useState("149");
	const prod = useRun();
	const plan = useRun();

	return (
		<Card
			num={3}
			title="Publish a service & appointment link"
			sub="POST /products + POST /plans + POST /calendar — each plan gets a public booking link."
		>
			{s.product ? (
				<div className="alert ok">
					Product <strong>{s.product.title}</strong> ·{" "}
					<span className="pill">{s.product.id}</span>
				</div>
			) : (
				<>
					<label>Service name</label>
					<input value={pTitle} onChange={(e) => setPTitle(e.target.value)} />
					<label>Description</label>
					<input value={pDesc} onChange={(e) => setPDesc(e.target.value)} />
					<button
						disabled={prod.busy}
						onClick={() =>
							prod.run(async () => {
								await api("/api/products", "POST", { title: pTitle, description: pDesc });
								await refresh();
							})
						}
					>
						{prod.busy ? "Creating…" : "Create product"}
					</button>
					<Status err={prod.err} />
				</>
			)}

			{s.product && (
				<>
					<div className="divider" />
					<label>Package name</label>
					<input value={planTitle} onChange={(e) => setPlanTitle(e.target.value)} />
					<label>Price (USD)</label>
					<input
						type="number"
						value={planPrice}
						onChange={(e) => setPlanPrice(e.target.value)}
					/>
					<button
						disabled={plan.busy}
						onClick={() =>
							plan.run(async () => {
								await api("/api/plans", "POST", {
									title: planTitle,
									price: planPrice,
								});
								await refresh();
							})
						}
					>
						{plan.busy ? "Creating…" : "Add package"}
					</button>
					<Status err={plan.err} />

					{s.plans.length > 0 && (
						<div style={{ marginTop: 6 }}>
							{s.plans.map((p) => (
								<div key={p.id} className="list-item">
									<div>
										{p.kind === "corporate" && <span className="badge">corporate</span>}{" "}
										<strong>{p.title}</strong> — ${p.price} ·{" "}
										<span className="pill">{p.id}</span>
									</div>
									<div style={{ marginTop: 6 }}>
										<a href={`/book/${p.id}`} target="_blank" rel="noreferrer">
											Open booking page ↗
										</a>
										{p.purchaseUrl && (
											<>
												{"  ·  "}
												<a href={p.purchaseUrl} target="_blank" rel="noreferrer">
													Whop checkout ↗
												</a>
											</>
										)}
									</div>
								</div>
							))}
						</div>
					)}
				</>
			)}
		</Card>
	);
}

function PlanSelect({
	plans,
	value,
	onChange,
}: {
	plans: Plan[];
	value: string;
	onChange: (v: string) => void;
}) {
	return (
		<select value={value} onChange={(e) => onChange(e.target.value)}>
			{plans.map((p) => (
				<option key={p.id} value={p.id}>
					{p.title} (${p.price})
				</option>
			))}
		</select>
	);
}

function FindCustomersStep({
	s,
	refresh,
}: {
	s: AppState;
	refresh: () => Promise<void>;
}) {
	const firstPlan = s.plans[0]?.id ?? "";
	const [refPlan, setRefPlan] = useState(firstPlan);
	const [adPlan, setAdPlan] = useState(firstPlan);
	const [headline, setHeadline] = useState("Showroom shine, parked in your driveway");
	const [primaryText, setPrimaryText] = useState("Book a full detail — we come to you this week.");
	const ref = useRun();
	const ad = useRun();

	useEffect(() => {
		if (!refPlan && firstPlan) setRefPlan(firstPlan);
		if (!adPlan && firstPlan) setAdPlan(firstPlan);
	}, [firstPlan, refPlan, adPlan]);

	if (s.plans.length === 0)
		return (
			<Card num={4} title="Find your first customers" sub="POST /ads + POST /referrals.">
				<p className="muted">Add a package first.</p>
			</Card>
		);

	return (
		<Card
			num={4}
			title="Find your first customers"
			sub="POST /ads + POST /referrals/products/:id — referral codes are honored at checkout."
		>
			<label>Referral link for</label>
			<PlanSelect plans={s.plans} value={refPlan} onChange={setRefPlan} />
			<button
				className="secondary"
				disabled={ref.busy}
				onClick={() =>
					ref.run(async () => {
						await api("/api/referrals", "POST", { planId: refPlan });
						await refresh();
					})
				}
			>
				{ref.busy ? "…" : "Generate referral link"}
			</button>
			<Status err={ref.err} />
			{s.referrals.map((r) => (
				<div key={r.code} className="list-item">
					code <span className="pill">{r.code}</span> →{" "}
					<a href={r.link} target="_blank" rel="noreferrer">
						{r.link}
					</a>
				</div>
			))}

			<div className="divider" />

			<label>Ad headline</label>
			<input value={headline} onChange={(e) => setHeadline(e.target.value)} />
			<label>Primary text</label>
			<input value={primaryText} onChange={(e) => setPrimaryText(e.target.value)} />
			<label>Drives to</label>
			<PlanSelect plans={s.plans} value={adPlan} onChange={setAdPlan} />
			<button
				disabled={ad.busy}
				onClick={() =>
					ad.run(async () => {
						await api("/api/ads", "POST", {
							headline,
							primaryText,
							cta: "Book now",
							budget: 50,
							planId: adPlan,
						});
						await refresh();
					})
				}
			>
				{ad.busy ? "…" : "Create ad"}
			</button>
			<Status err={ad.err} />
			{s.ads.map((a) => (
				<div key={a.id} className="list-item">
					<strong>{a.headline}</strong>
					<div className="muted">{a.primaryText}</div>
					<a href={a.link} target="_blank" rel="noreferrer">
						{a.link}
					</a>
				</div>
			))}
		</Card>
	);
}

function MoneyStep({ s }: { s: AppState }) {
	const [email, setEmail] = useState("");
	const [name, setName] = useState("");
	const [amount, setAmount] = useState("40");
	const [desc, setDesc] = useState("Extra interior shampoo");
	const [ok, setOk] = useState<string | null>(null);
	const { busy, err, setErr, run } = useRun();

	return (
		<Card
			num={5}
			title="Get paid"
			sub="Embedded Whop balance + withdrawals, and POST /invoices for add-ons (auto-charges the customer)."
		>
			<PayoutsPanel companyId={s.config.activeCompanyId} />

			<div className="divider" />
			<p className="muted">Send an invoice for an extra charge:</p>
			<div className="row">
				<div>
					<label>Customer email</label>
					<input value={email} onChange={(e) => setEmail(e.target.value)} />
				</div>
				<div>
					<label>Customer name</label>
					<input value={name} onChange={(e) => setName(e.target.value)} />
				</div>
			</div>
			<div className="row">
				<div>
					<label>Amount (USD)</label>
					<input
						type="number"
						value={amount}
						onChange={(e) => setAmount(e.target.value)}
					/>
				</div>
				<div>
					<label>For</label>
					<input value={desc} onChange={(e) => setDesc(e.target.value)} />
				</div>
			</div>
			<button
				disabled={busy}
				onClick={() => {
					setOk(null);
					setErr(null);
					run(async () => {
						const inv = await api<{ number?: string; status?: string; id: string }>(
							"/api/invoices",
							"POST",
							{ email, name, amount, description: desc },
						);
						setOk(`Invoice ${inv.number ?? inv.id} created (${inv.status ?? "pending"}).`);
					});
				}}
			>
				{busy ? "Sending…" : "Create invoice"}
			</button>
			<Status err={err} ok={ok} />
		</Card>
	);
}

function FriendsStep({ s, refresh }: { s: AppState; refresh: () => Promise<void> }) {
	const [name, setName] = useState("Alex");
	const [email, setEmail] = useState("");
	const [payFriend, setPayFriend] = useState("");
	const [payAmount, setPayAmount] = useState("75");
	const [slotPlan, setSlotPlan] = useState(s.plans[0]?.id ?? "");
	const [slot, setSlot] = useState("");
	const hire = useRun();
	const pay = useRun();
	const cal = useRun();
	const [payOk, setPayOk] = useState<string | null>(null);

	return (
		<Card
			num={6}
			title="Hire friends & run payroll"
			sub="POST /accounts (friend) + POST /transfers (payroll) + PATCH /calendar (their availability)."
		>
			<label>Friend's name</label>
			<input value={name} onChange={(e) => setName(e.target.value)} />
			<label>Their email (optional)</label>
			<input value={email} onChange={(e) => setEmail(e.target.value)} />
			<button
				disabled={hire.busy}
				onClick={() =>
					hire.run(async () => {
						await api("/api/friends", "POST", { name, email });
						await refresh();
					})
				}
			>
				{hire.busy ? "…" : "Hire detailer"}
			</button>
			<Status err={hire.err} />

			{s.friends.length > 0 && (
				<>
					{s.friends.map((f) => (
						<div key={f.id} className="list-item">
							<strong>{f.name}</strong> · <span className="pill">{f.id}</span>
						</div>
					))}

					<div className="divider" />
					<label>Pay</label>
					<select
						value={payFriend || s.friends[0]?.id}
						onChange={(e) => setPayFriend(e.target.value)}
					>
						{s.friends.map((f) => (
							<option key={f.id} value={f.id}>
								{f.name}
							</option>
						))}
					</select>
					<label>Amount (USD)</label>
					<input
						type="number"
						value={payAmount}
						onChange={(e) => setPayAmount(e.target.value)}
					/>
					<button
						disabled={pay.busy}
						onClick={() => {
							setPayOk(null);
							pay.run(async () => {
								const t = await api<{ id?: string }>("/api/payroll", "POST", {
									friendId: payFriend || s.friends[0]?.id,
									amount: payAmount,
								});
								setPayOk(`Transfer sent${t.id ? ` (${t.id})` : ""}.`);
							});
						}}
					>
						{pay.busy ? "Sending…" : "Run payroll"}
					</button>
					<Status err={pay.err} ok={payOk} />
				</>
			)}

			{s.plans.length > 0 && (
				<>
					<div className="divider" />
					<p className="muted">Add availability (e.g. a friend's open slot):</p>
					<label>Package</label>
					<PlanSelect
						plans={s.plans}
						value={slotPlan || s.plans[0].id}
						onChange={setSlotPlan}
					/>
					<label>New slot</label>
					<input
						type="datetime-local"
						value={slot}
						onChange={(e) => setSlot(e.target.value)}
					/>
					<button
						className="secondary"
						disabled={cal.busy || !slot}
						onClick={() =>
							cal.run(async () => {
								await api("/api/calendar", "PATCH", {
									planId: slotPlan || s.plans[0].id,
									slots: [new Date(slot).toISOString()],
								});
								setSlot("");
								await refresh();
							})
						}
					>
						{cal.busy ? "…" : "Add slot"}
					</button>
					<Status err={cal.err} />
				</>
			)}
		</Card>
	);
}

function SpecialRateStep({
	s,
	refresh,
}: {
	s: AppState;
	refresh: () => Promise<void>;
}) {
	const [title, setTitle] = useState("Acme Corp employee rate");
	const [price, setPrice] = useState("99");
	const { busy, err, run } = useRun();
	const [ok, setOk] = useState<string | null>(null);

	return (
		<Card
			num={7}
			title="Offer a corporate special rate"
			sub="POST /plans + POST /calendar — a discounted plan for a company's employees."
		>
			{!s.product ? (
				<p className="muted">Create a product first.</p>
			) : (
				<>
					<label>Offer name</label>
					<input value={title} onChange={(e) => setTitle(e.target.value)} />
					<label>Employee price (USD)</label>
					<input type="number" value={price} onChange={(e) => setPrice(e.target.value)} />
					<button
						disabled={busy}
						onClick={() => {
							setOk(null);
							run(async () => {
								const p = await api<{ bookingLink: string }>(
									"/api/special-rate",
									"POST",
									{ title, price },
								);
								setOk(`Corporate plan live: ${p.bookingLink}`);
								await refresh();
							});
						}}
					>
						{busy ? "Creating…" : "Create corporate rate"}
					</button>
					<Status err={err} ok={ok} />
				</>
			)}
		</Card>
	);
}

// ---------- root ----------

export function Dashboard() {
	const [s, setS] = useState<AppState | null>(null);
	const [loadErr, setLoadErr] = useState<string | null>(null);

	const refresh = useCallback(async () => {
		try {
			setS(await api<AppState>("/api/state", "GET"));
		} catch (e) {
			setLoadErr(e instanceof Error ? e.message : String(e));
		}
	}, []);

	useEffect(() => {
		refresh();
	}, [refresh]);

	return (
		<div className="wrap">
			<header className="hero">
				<h1>🚗 Shine — start a car-detailing business on Whop</h1>
				<p>Go from idea to first paid booking, end-to-end, on real Whop infrastructure.</p>
			</header>

			{loadErr && <div className="alert err">{loadErr}</div>}
			{!s && !loadErr && <p className="muted">Loading…</p>}

			{s && s.config.missingEnv.length > 0 && (
				<div className="alert warn">
					Missing required env: <strong>{s.config.missingEnv.join(", ")}</strong>. Add it
					to <span className="pill">.env.local</span> and restart. See{" "}
					<span className="pill">.env.example</span>.
				</div>
			)}

			{s && (
				<>
					<BusinessStep s={s} refresh={refresh} />
					<IdeasStep hasAnthropic={s.config.hasAnthropic} />
					<ProductPlansStep s={s} refresh={refresh} />
					<FindCustomersStep s={s} refresh={refresh} />
					<MoneyStep s={s} />
					<FriendsStep s={s} refresh={refresh} />
					<SpecialRateStep s={s} refresh={refresh} />
				</>
			)}
		</div>
	);
}
